name: Generate Stats Images

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          ref: templates

      - name: Download Latest Release
        run: gh release download --pattern github-stats-rs-arm
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Make Latest Release executable
        run: chmod +x ./github-stats-rs-arm

      - name: Generate images
        run: ./github-stats-rs-arm
        env:
          TEMPLATE_FOLDER: "."
          OUTPUT_FOLDER: "."
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Commit to the repo
        run: |
          git checkout generated
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m 'Update generated files' || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
